### ISSUE TITLE
npm ERR! Failed at the vue-test@1.0.0 e2e script 'node test/e2e/runner.js'.

### ISSUE THREAD

**Issue by arightious** [callumacrae/vue-test#10]
I'm trying to run the nightwatch e2e tests in Vue. I've been poking around for awhile and always end up with some selenium related errors.

Here's the error I'm getting:

```
Starting selenium server... started - PID:  13452

[Test] Test Suite
=====================

Running:  default e2e tests

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ state: 'unhandled error',
  sessionId: null,
  hCode: 902387334,
  value: 
   { localizedMessage: null,
     cause: null,
     suppressed: [],
     message: null,
     hCode: 1853718195,
     class: 'java.util.concurrent.TimeoutException',
     screen: null },
  class: 'org.openqa.selenium.remote.Response',
  status: 13 }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-test@1.0.0 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-test@1.0.0 e2e script 'node test/e2e/runner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/e2e/runner.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-test
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/**********/.npm/_logs/2017-03-24T21_38_04_011Z-debug.log
```

This is the log referenced:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'e2e' ]
2 info using npm@4.4.1
3 info using node@v6.10.1
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle vue-test@1.0.0~pree2e: vue-test@1.0.0
6 silly lifecycle vue-test@1.0.0~pree2e: no script for pree2e, continuing
7 info lifecycle vue-test@1.0.0~e2e: vue-test@1.0.0
8 verbose lifecycle vue-test@1.0.0~e2e: unsafe-perm in lifecycle true
9 verbose lifecycle vue-test@1.0.0~e2e: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/**********/selenium/ui-vue/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle vue-test@1.0.0~e2e: CWD: /Users/**********/selenium/ui-vue
11 silly lifecycle vue-test@1.0.0~e2e: Args: [ '-c', 'node test/e2e/runner.js' ]
12 silly lifecycle vue-test@1.0.0~e2e: Returned: code: 1  signal: null
13 info lifecycle vue-test@1.0.0~e2e: Failed to exec e2e script
14 verbose stack Error: vue-test@1.0.0 e2e: `node test/e2e/runner.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-test@1.0.0
16 verbose cwd /Users/**********/selenium/ui-vue
17 verbose Darwin 16.4.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
19 verbose node v6.10.1
20 verbose npm  v4.4.1
21 error code ELIFECYCLE
22 error errno 1
23 error vue-test@1.0.0 e2e: `node test/e2e/runner.js`
23 error Exit status 1
24 error Failed at the vue-test@1.0.0 e2e script 'node test/e2e/runner.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the vue-test package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node test/e2e/runner.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs vue-test
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls vue-test
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by callumacrae** [comment]
Are you using vue-test in your e2e tests? Interesting, I've only seen it used for unit tests until now :)

Could you post some failing code? Also, does it work if you take vue-test out?

**Comment by pedroskakum** [comment]
I have a similar problem in "runner.js", however, without using vue-test:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/pedroskakum/.nvm/v6.11.2/bin/node',
1 verbose cli   '/home/pedroskakum/.nvm/v6.11.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle app-client@1.0.0~pretest: app-client@1.0.0
6 silly lifecycle app-client@1.0.0~pretest: no script for pretest, continuing
7 info lifecycle app-client@1.0.0~test: app-client@1.0.0
8 verbose lifecycle app-client@1.0.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle app-client@1.0.0~test: PATH: /home/pedroskakum/.nvm/v6.11.2/lib/node_modules/npm/bin/node-gyp-bin:/var/www/app-client/node_modules/.bin:./node_modules/.bin:/home/pedroskakum/.nvm/v6.11.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle app-client@1.0.0~test: CWD: /var/www/app-client
11 silly lifecycle app-client@1.0.0~test: Args: [ '-c', 'npm run unit && npm run e2e' ]
12 silly lifecycle app-client@1.0.0~test: Returned: code: 1  signal: null
13 info lifecycle app-client@1.0.0~test: Failed to exec test script
14 verbose stack Error: app-client@1.0.0 test: `npm run unit && npm run e2e`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/pedroskakum/.nvm/v6.11.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/pedroskakum/.nvm/v6.11.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid app-client@1.0.0
16 verbose cwd /var/www/app-client
17 error Linux 4.9.0-deepin4-amd64
18 error argv "/home/pedroskakum/.nvm/v6.11.2/bin/node" "/home/pedroskakum/.nvm/v6.11.2/bin/npm" "run" "test"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error app-client@1.0.0 test: `npm run unit && npm run e2e`
22 error Exit status 1
23 error Failed at the app-client@1.0.0 test script 'npm run unit && npm run e2e'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run unit && npm run e2e
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
